baseURL = 'https://portfolio-thanle.vercel.app/' # Sau nÃ y sáº½ sá»­a láº¡i sau
languageCode = 'vi'
title = 'Blog Láº­p TrÃ¬nh Cá»§a ThÃ¢n LÃª'
theme = 'PaperMod'

[params]
  defaultTheme = "light"
  
  [params.homeInfoParams]
    Title = "Hi there, I'm Than Le ğŸ‘‹"
    Content = "Sinh viÃªn pháº§n má»m / Blogger cÃ´ng nghá»‡. ChÃ o má»«ng báº¡n Ä‘áº¿n vá»›i blog cÃ¡ nhÃ¢n cá»§a tÃ´i."
    
  # Cáº¥u hÃ¬nh Ä‘á»ƒ hiá»‡n áº£nh Ä‘áº¡i diá»‡n
  [params.profileMode]
    enabled = true
    title = "Hi there, I'm Than Le" # TÃªn hiá»‡n to Ä‘Ã¹ng
    subtitle = "Sinh viÃªn pháº§n má»m / Blogger cÃ´ng nghá»‡"
    imageUrl = "avatar.jpg" # ÄÆ°á»ng dáº«n áº£nh (nÃ³ tá»± láº¥y trong thÆ° má»¥c static)
    imageTitle = "Avatar"
    imageWidth = 260 # KÃ­ch thÆ°á»›c áº£nh (cÃ ng to cÃ ng rÃµ)
    imageHeight = 180
    buttons = [
        { name = "About Me", url = "/about" },
        { name = "Blog", url = "/posts" }
    ]

  # CÃ¡c icon máº¡ng xÃ£ há»™i bÃªn dÆ°á»›i
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/ThanLe04"
  [[params.socialIcons]]
    name = "facebook"
    url = "https://www.facebook.com/thanleloveu"
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Blog Láº­p TrÃ¬nh"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "ğŸ” TÃ¬m Kiáº¿m"
    url = "/search/"
    weight = 25
[outputs]
    home = ["HTML", "RSS", "JSON"]